site_name: hypercli
docs_dir: docs
repo_url: https://github.com/HYP3R00T/hypercli
repo_name: HYP3R00T/hypercli
theme:
  icon:
    logo: octicons/terminal-24
    menu: material/dots-grid
    search: octicons/search-24
  name: "material"
  palette:
    primary: custom
    accent: custom
    scheme: dark
  font:
    text: Inter
    code: Source Code Pro
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    # - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.prune
    - navigation.indexes
    - navigation.footer
    - toc.follow
    - content.code.copy
    - search.suggest
    # - search.highlight
    - search.share
    - content.action.edit
    - content.action.view
plugins:
  - search
  - roamlinks
  - callouts
  - termynal:
      title: shell
      buttons: windows
      prompt_literal_start:
        - ">"
  - tags
  - social:
      cards_layout_options:
        background_color: "#1e1e2e"
        color: "#cdd6f4"
markdown_extensions:
  - footnotes
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
extra_javascript:
  # - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/HYP3R00T
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rajesh-kumar-das/
    # - icon: fontawesome/brands/x-twitter
    #   link: https://twitter.com/HYP3R00T
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@hyperoot
    - icon: octicons/person-fill-24
      link: https://hyperoot.dev/
  status:
    new: Recently added
extra_css:
  - stylesheets/extra.css
copyright: Copyright &copy; 2025 hyperoot.dev
